### ISSUE TITLE
Emails: make display name be "Full House"

### ISSUE THREAD

**Issue by natmote** [Full-House-UW/fullhouse#103]
Right now, the email display name is "accounts," which is not very informative.

**Comment by j3ffml** [comment]
I believe you can fix this by setting the DEFAULT_FROM_EMAIL to be a `'name <email>'` string, e.g. 

``` python
DEFAULT_FROM_EMAIL = 'Do Not Reply <do_not_reply@fullhousemanager.com>'
```

This should be done in local.py on the server.

On that note, we should probably have do_not_reply in the name or email we send, as I don't think we're checking those.

**Comment by natmote** [comment]
Thanks for the tip, jeff. I've fixed it.
