### ISSUE TITLE
Registration Page to direct to log-in, not an intermediate successfully logged out page

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#111]

**Comment by creisman** [comment]
We'll add status message displays in welcome and dashboard in the next release and do this there.

**Comment by j3ffml** [comment]
@snuriel92, do you mean the activation page? The registration page directs to a 'activation link sent' page, which I think is the correct behavior. AFAIK the activation page redirects to the dashboard so I'm not sure what this is talking about.

**Comment by JSiu** [comment]
I think the idea was to redirect to the login page, which would display a message saying "Activation email sent," instead of an entirely different page that would require them to make an extra click to get somewhere useful.

**Comment by creisman** [comment]
#277
