### ISSUE TITLE
Allow Dashboard access without creating a house (give as an option when told you're not part of a house)

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#112]
Is user still going to be able to post things on this Dashboard page that is not associated with a house?  What would happen after user joins house?

Allow option of Creating a House later then in case they want to just create it way later?

**Comment by bkgomez** [comment]
I think they should have to be part of a house in order to post things, as the purpose of posting things is for other people in the same house to see it.

**Comment by snuriel92** [comment]
Ya, just deleting this
