### ISSUE TITLE
missing logout button on 'you are not a member of a house' page

### ISSUE THREAD

**Issue by j3ffml** [Full-House-UW/fullhouse#124]
Can't logout if I don't have a house... doesn't seem right.

**Comment by snuriel92** [comment]
Ya, that's annoying but at the same time. they can click "skip for now and log out" so it's not AS major of an issue

**Comment by creisman** [comment]
I cannot reproduce this bug. The header links show up just fine for me. The template uses user.is_authenticated to decide whether or not to display them, so it's a problem with auth if you're still having this problem.

**Comment by creisman** [comment]
Are you still having this problem or can we resolve as "cannot duplicate"?

**Comment by snuriel92** [comment]
I don't get this one either

**Comment by JSiu** [comment]
I can't repro; @jlowdermilk, are you still seeing this?

**Comment by j3ffml** [comment]
no, I'm pretty sure it got fixed already.
