### ISSUE TITLE
Unused template?

### ISSUE THREAD

**Issue by natmote** [Full-House-UW/fullhouse#135]
I don't believe we're using create_house.html. can it be deleted?

**Comment by JSiu** [comment]
Isn't that the template that gets shown when a user registers but isn't part of a house yet, so we ask them if they want to make one?

**Comment by snuriel92** [comment]
I think that might be nonhousememeber.html?

**Comment by natmote** [comment]
Looks like we've determined that this is unnecessary (#140)
