### ISSUE TITLE
No options for gender in user settings form.

### ISSUE THREAD

**Issue by creisman** [Full-House-UW/fullhouse#142]
If you open user settings, the gender label has no form element associated with it.

**Comment by creisman** [comment]
This actually appears to be happening because it's not in the model. Can you add it Jeff?

**Comment by j3ffml** [comment]
Better to have Nat add it, as it requires a migration.

On Sun, Nov 18, 2012 at 3:54 PM, Conor Reisman notifications@github.comwrote:

> This actually appears to be happening because it's not in the model. Can
> you add it Jeff?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Full-House-UW/fullhouse/issues/142#issuecomment-10497644.

## 

Jeff L

**Comment by natmote** [comment]
Does this need to happen this release?

**Comment by JSiu** [comment]
No, I could just delete it from the template.

Janette Siu

---

Be more concerned with your character than your reputation, because your
character is what you really are, while your reputation is merely what
others think you are.
- Coach John Wooden, 1910-2010

**Comment by creisman** [comment]
Lets do that for this release and punt it to next release.

**Comment by natmote** [comment]
punted to final release

**Comment by creisman** [comment]
#157 to remove the gender field for now.

**Comment by j3ffml** [comment]
Depends on #188

**Comment by j3ffml** [comment]
I'm marking this as duplicate. #188 will take care of user attributes that are specifiable on the settings page.
