### ISSUE TITLE
All fields in user settings should be optional.

### ISSUE THREAD

**Issue by creisman** [Full-House-UW/fullhouse#144]
A user should be able to update their email without adding a birthday etc.

**Comment by creisman** [comment]
These should be made optional in the form (or model?).

**Comment by j3ffml** [comment]
In the form. The fields of the user settings form don't correspond
one-to-one with a single model. It has fields from both User and
UserProfile, some of which are required (e.g. email for Users).

On Sun, Nov 18, 2012 at 3:55 PM, Conor Reisman notifications@github.comwrote:

> These should be made optional in the form (or model?).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Full-House-UW/fullhouse/issues/144#issuecomment-10497658.

## 

Jeff L
