### ISSUE TITLE
Verify changed emails

### ISSUE THREAD

**Issue by creisman** [Full-House-UW/fullhouse#145]
If the user changes the email, we need to re-verify.

**Comment by snuriel92** [comment]
Should they even be allowed to do that? I feel like this is like a username and you should not really change it?

**Comment by j3ffml** [comment]
Open question then. We can allow them to change and reverify, of not allow changes. What do we want?

**Comment by JSiu** [comment]
I think we should allow changing emails; some people migrate from one email to another, and don't want to be permanently tied to one address.

**Comment by JSiu** [comment]
It's not like it's any less unique...

**Comment by natmote** [comment]
yeah, I think we should allow it. currently, it lets you change, but it doesn't re-verify, which seems like a bit of a hole. It's probably not that hard to make it reverify, is it?

**Comment by creisman** [comment]
But what do we do while it's pending? Keep the old one? Lock them out again? Let it work for a while with an unverified account?

We could also drop the email field in settings for this release and make a more thought-out choice next release. Is there any pressure to get this in this release?

Leaving it out also solves #144 since it'd be the only changeable option.

**Comment by JSiu** [comment]
I'd say it would make the most sense to keep the old one until they've
verified the new one.

Janette Siu

---

Be more concerned with your character than your reputation, because your
character is what you really are, while your reputation is merely what
others think you are.
- Coach John Wooden, 1910-2010

**Comment by j3ffml** [comment]
It sounds like we don't have a definite answer on this. Shall we just take out the email for this release? That will give us more time to decide how to allow them to change their email.

**Comment by JSiu** [comment]
Sure, that sounds like the easiest option.

Janette Siu

---

Be more concerned with your character than your reputation, because your
character is what you really are, while your reputation is merely what
others think you are.
- Coach John Wooden, 1910-2010

**Comment by creisman** [comment]
But that's very confusing to users if they log out and try to log back in with their new email and suddenly it doesn't work because they haven't verified yet. Perhaps if we check that there's a pending transition and tell them to log in using their old email, but that's a lot of work.

We could also leave it as is and explain that we use activation as a way to make sure the user is real, but we don't actually care if the email is real. As long as we know it's a real user on the other end they can change their email to be anything they want. This takes away from the "verifying email" and makes it "verifying account". If we explain it that way, we wouldn't need to re-verify because we've already verified their account and don't care about their email.

I'm up for any of these solutions, but am tempted to go with whatever solution is easiest. In my mind that means the one I detailed above, which is no code change and a paragraph in our write-up, or remove the ability to change it in our settings, which just runs the risk of it being the lack of a reasonable feature (might have to write a paragraph saying it's coming in the future as well).

**Comment by JSiu** [comment]
In reality, the most graceful option would be to allow them to add/delete email address, and disallow them from deleting their last verified email address.  However, that's certainly not something we're going to get out in this release, and maybe not the next one either; depends on what we decide are our priorities at our meeting tomorrow.  For this release, we can just cut the email field from the user settings; then they can't complain that our provided functionality is flawed.

**Comment by j3ffml** [comment]
We've decided not to allow changing emails.
