### ISSUE TITLE
Add members at any time

### ISSUE THREAD

**Issue by creisman** [Full-House-UW/fullhouse#146]
We should be able to invite members to join at any time, not just during house creation. I think this was specifically mentioned in our review by Wayne last release.

**Comment by j3ffml** [comment]
Actually, we can add members at any time. We just don't have a link to the add members page on the dashboard. put that link in, and we can close this.

**Comment by creisman** [comment]
Okay, shall I take over this bug then?

**Comment by j3ffml** [comment]
Yes please, if you would.

**Comment by creisman** [comment]
For this release I'm going to give it its own link in the header. In the future we should merge it with another page or link to it from somewhere else.

**Comment by creisman** [comment]
#152
