### ISSUE TITLE
Old announcements don't show up

### ISSUE THREAD

**Issue by natmote** [Full-House-UW/fullhouse#154]
I believe this has to do with the newly introduced expiration field.

In QA, old announcements don't show up after the upgrade.

**Comment by natmote** [comment]
I've confirmed that this is due to a null announcements expiration field

**Comment by natmote** [comment]
I'm actually going to fix this.

**Comment by creisman** [comment]
Oh, right, didn't think of this. I defaulted announcements to expire in two weeks, so I would recommend setting null expirations to two weeks from today.

**Comment by natmote** [comment]
For now, I'm just going to display null expirations. I think it makes sense to allow non-expiring announcements anyway, so maybe we can add that in the future?

**Comment by creisman** [comment]
SGTM. It's a nice quick fix.

**Comment by j3ffml** [comment]
I would agree that makes sense. If the announcement has no expirationdate,
then it should not expire.

On Sun, Nov 18, 2012 at 3:53 PM, Nathaniel Mote notifications@github.comwrote:

> For now, I'm just going to display null expirations. I think it makes
> sense to allow non-expiring announcements anyway, so maybe we can add that
> in the future?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Full-House-UW/fullhouse/issues/154#issuecomment-10497621.

## 

Jeff L

**Comment by natmote** [comment]
#156
