### ISSUE TITLE
Test IE compatibility

### ISSUE THREAD

**Issue by creisman** [Full-House-UW/fullhouse#158]
Since we're tied into developing in Linux it's kind of hard to test IE. I'm proposing that for now compatibility is tested during the test release cycle and CSS only changes can be pushed if necessary. The documentation must also be updated to indicate which browsers are support. I believe IE9+ is supported (aside from possibly non-breaking CSS changes). IE8 might be worse but I think there's a decent chance it will work. I have no IE8-compatible computer, though, so someone else will have to test this level.

Assigning to @JSiu because she's in charge of managing docs.

**Comment by JSiu** [comment]
Javascript not working on Create House page in IE8.

**Comment by creisman** [comment]
#218

**Comment by creisman** [comment]
I think we're good here so I'm closing it.
