### ISSUE TITLE
Login broken in IE

### ISSUE THREAD

**Issue by creisman** [Full-House-UW/fullhouse#161]
When I try and login in IE (test.fullhousemanager.com, post email transition), it redirects me to the login page again (with next=dashboard). So it's successfully saying we logged in, but then not giving me the auth cookie correctly (or something). Happened on both IE9 and IE10.

It'd be great to get this in this release if you can think of what would cause it and fix it fast, otherwise punt to the next release. We'll put in our release notes that we "had a conflict" in IE that will be fixed for next release.

**Comment by j3ffml** [comment]
I tried to log in in IE9 and had no problems. Does anyone else have this bug?

**Comment by creisman** [comment]
I like the sound of that... I'll have some other people test it
independently of me. I wouldn't be surprised if I have some weird settings
in IE that are causing the conflict.

**Comment by JSiu** [comment]
I can't repro this bug either; I also have IE9.

**Comment by natmote** [comment]
I just tried it on IE9 under windows 7, and it worked fine.

**Comment by snuriel92** [comment]
I can log in on IE 8

**Comment by snuriel92** [comment]
I can't create a house on IE8 though...

**Comment by creisman** [comment]
Shahaf, is it the JavaScript that's broken? Or the form?

**Comment by JSiu** [comment]
Create House is working on IE9.

**Comment by creisman** [comment]
IE10 is now working for me, so I don't know what was going on last night. I
don't have IE8 to test the create house error, so I don't know if I can get
a fix in for that tonight.

**Comment by snuriel92** [comment]
Sorry, I didn't reproduce the error and someone came to talk to me so I wasn't able to work on this but it works for Janette so we should be good!

**Comment by JSiu** [comment]
We might should double-check IE8 on this, because I was using IE9.

**Comment by snuriel92** [comment]
The javascript isn't working on IE8

**Comment by creisman** [comment]
I'll try and get a VM with IE8 running to test it but no promises that
it'll be soon... When's the release? We may also want to drop IE8 support.
It is now officially 2 versions old.

**Comment by JSiu** [comment]
Let's punt this particular issue to the next release. This release is
supposedly in -22 minutes.

**Comment by creisman** [comment]
Ha ha alright. Lack of IE8 support shouldn't be a big deal.

**Comment by snuriel92** [comment]
I searched for a "like" button on the last posts.... clearly I'm spending too much time on Facebook
