### ISSUE TITLE
A user should be able to remove themselves from a house.

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#173]

**Comment by j3ffml** [comment]
Can users remove other members from a house? How?

**Comment by JSiu** [comment]
A member can only remove themselves from a house.  (When we implement admins, admins can remove anybody from a house.)

On the House Settings page, there should be a link to remove yourself from the house.  When a user clicks on that link, they will need to confirm that they want to remove themselves.  If they are the last person in the house, they will get a customized confirmation page that also mentions that removing themselves will delete their house and all of its associated announcements and tasks.

**Comment by j3ffml** [comment]
Resolved by #223
