### ISSUE TITLE
Authentication pages should redirect when user is logged in

### ISSUE THREAD

**Issue by creisman** [Full-House-UW/fullhouse#177]
While logged in, you should not be able to access /accounts/login/ or any of the password recovery/reset pages. I believe login should redirect to dashboard and the recovery/reset pages should logout and then function as normal. There is no security risk that I could spot (changes the correct account), so I think this is fine for next release.

**Comment by j3ffml** [comment]
Assigned to @natmote

**Comment by j3ffml** [comment]
closed by #215
