### ISSUE TITLE
Users should be able to create and edit periodic tasks

### ISSUE THREAD

**Issue by j3ffml** [Full-House-UW/fullhouse#191]
- Task is defined with a frequency
- Tasks define a list of participants
- Completing a task puts an instance of that task in the history as completed by the person who clicked complete
- The next task is automatically assigned to the next participant
- Overdue task instances are put into history as incomplete (can be edited to mark as complete)

**Comment by snuriel92** [comment]
So we are allowing anyone to clock "complete" on a task, right? Maybe we should track who clicked it so we can display in the history:
Assigned to: Conor 
Checked complete by: Shahaf

**Comment by j3ffml** [comment]
@snuriel92, that feature is already implemented. I will have pull request when I finish tests

**Comment by j3ffml** [comment]
Closed by #212
