### ISSUE TITLE
Adding members should be done from House Settings page, not nav bar

### ISSUE THREAD

**Issue by JSiu** [Full-House-UW/fullhouse#192]
Adding members doesn't happen very often, so it probably shouldn't be shown on every page with the nav bar.

**Comment by creisman** [comment]
Did you want this Cornel? It wasn't taken in the schedule doc so I was going to take it since I'll be working on adding multiple forms. This either needs to be done quickly or you should assign it to me. Thanks!

**Comment by JSiu** [comment]
Conor, this is more front-end and wraps really easily into your other task, so I'm going to assign it to you.

**Comment by creisman** [comment]
SGTM. I'd already claimed it in the schedule and was planning on stealing it here too :P.

**Comment by creisman** [comment]
#216
