### ISSUE TITLE
All pages should be able to display temporary messages

### ISSUE THREAD

**Issue by j3ffml** [Full-House-UW/fullhouse#193]
Put a message div in the base template that only appears if a 'message' is passed to the template engine. load some js that makes it visible for a few seconds if there is a message passed in. This should work on all pages so that e.g. #111 can be implemented.

**Comment by JSiu** [comment]
Add a parameter that specifies how long it should be displayed, and if no parameter is specified, then it doesn't disappear (until page reload)?

**Comment by creisman** [comment]
#208.
usage
url?error=optionalerrormessagehere&message=optionalinfomessagehere&time=optionaltimeouthere.
