### ISSUE TITLE
Anybody should be able to edit/delete tasks

### ISSUE THREAD

**Issue by JSiu** [Full-House-UW/fullhouse#204]
All the people in a house should be able to edit/delete the tasks created by other members.

**Comment by creisman** [comment]
I can handle this once Nat migrates and merges your pull request. I have something working once that's done.

**Comment by j3ffml** [comment]
@creisman, I'm actually already taking care of it in updated pull request.

**Comment by creisman** [comment]
Alright, sounds good.

**Comment by j3ffml** [comment]
Closed by #212
