### ISSUE TITLE
Users should need to confirm they want to switch houses

### ISSUE THREAD

**Issue by JSiu** [Full-House-UW/fullhouse#205]
If a user is invited to a house, but they're already a member of a different house, the link in the invitation email should take them to a page that asks them to confirm that they want to leave their house and join the other.  Saying either yes or no should redirect them to their dashboard page.

**Comment by JSiu** [comment]
Talk to @jlowdermilk as necessary to make sure we correctly remove them from their existing house if they confirm that they want to switch.

**Comment by creisman** [comment]
@jlowdermilk Is there a way to test the validity of an invite without accepting?

**Comment by j3ffml** [comment]
@creisman: there is. Look at `InviteManager` in `models.py`. Basically, you look up the inviteprofile by the sha1 in the link (the invite_key). If it exists, is not expired and the emails match, it's a valid invite.

**Comment by creisman** [comment]
#272
