### ISSUE TITLE
Site should display custom 404, 403 pages

### ISSUE THREAD

**Issue by j3ffml** [Full-House-UW/fullhouse#210]
Pretty simple to do, just need to define `handler404` and `handler403` in the root `url.py`, and have templates for them. Then `HttpResponseNotFound` and `HttpResponseForbidden` will direct to our pages.

Then we can have more sensible handling in all the #TODOs  in dashboard views where we currently just redirect to the dashboard if the request cannot be served because it's invalid/don't have permission, etc.

**Comment by bkgomez** [comment]
I'm assuming the templates should give the user the option of returning to the dashboard?

**Comment by j3ffml** [comment]
@bkgomez, I would say so. they can either extend the base template or just put have a link back to dashboard.
