### ISSUE TITLE
Make tasks prettier

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#231]
More readable (at least some bolding in there). Also, missing a closing ) in the description:
http://i49.tinypic.com/1zgwa6q.jpg

**Comment by snuriel92** [comment]
Also, separate between the tasks more.
Display task history so it's a bit prettier (and more moved up, not almost off the area for it)

**Comment by JSiu** [comment]
Also, less space between the lines of a single task on the dashboard so we can fit more tasks on one page and they look more cohesive. Tasks just need a UI/UX overhaul; it isn't clear how to interact with them and what all the fields mean.

**Comment by snuriel92** [comment]
I worked on this too. Merging tomorrow.
