### ISSUE TITLE
"Complete" on Edit Task screen should give some feedback

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#232]
Marking "complete" in Edit Tasks doesn't do anything (I think) or should at the very least re-direct to the dashboard.

**Comment by JSiu** [comment]
@snuriel92, not sure what you mean here. There isn't a Complete button for Edit Task. Can you elaborate?

**Comment by snuriel92** [comment]
Ya, no idea what I was thinking. I also don't even remember writing this.
