### ISSUE TITLE
On error, pages should populate error messages

### ISSUE THREAD

**Issue by JSiu** [Full-House-UW/fullhouse#247]
instead of redirecting to Dashboard

**Comment by snuriel92** [comment]
Maybe we should also add that when a task gets completed, we give a message saying "Cleaning Bathroom got completed on Dec 5, 2012; was due Dec 6, 2012"?

**Comment by snuriel92** [comment]
@creisman didn't you already do this?

**Comment by creisman** [comment]
No, I added the ability to do it, but I did not populate any of them. I can't do this until Brandon is done so I know what to set and what will be handled by 404 and 403 pages.

**Comment by creisman** [comment]
#277
