### ISSUE TITLE
Login in IE fails

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#264]
I log into our test site in IE and it doesn't log in. If the password and username are correct, I just get redirected to the welcome page with blank boxes for email and pw. When I actually put in incorrect ones, I get the error message about them being incorrect. 
When I log in on Chrome, it all works.
(IE 8)

**Comment by snuriel92** [comment]
Apparently it works on other IEs though...

**Comment by creisman** [comment]
#161

**Comment by creisman** [comment]
We could never duplicate this before.

**Comment by snuriel92** [comment]
Closing due to inability to replicate
