### ISSUE TITLE
Serve static media on webfaction

### ISSUE THREAD

**Issue by natmote** [Full-House-UW/fullhouse#32]

**Comment by j3ffml** [comment]
As soon as https://github.com/Full-House-UW/fullhouse/pull/31 is merged, we
should probably do a prototype release and get it running on webfaction.

On Sun, Oct 21, 2012 at 10:51 AM, Nathaniel Mote
notifications@github.comwrote:

>  —
> Reply to this email directly or view it on GitHubhttps://github.com/Full-House-UW/fullhouse/issues/32.

## 

Jeff L

**Comment by natmote** [comment]
yes, I've got everything working, and I'm working on getting a release script hacked together now.
