### ISSUE TITLE
Browser window resize causes “Announcements” and “Tasks” panes to float out of place.

### ISSUE THREAD

**Issue by cmoiceanu** [Full-House-UW/fullhouse#80]
Link to screenshot
http://dl.dropbox.com/u/88614194/FullHouse_UI_FormResize_001.PNG

Browser window resize causes “Announcements” and “Tasks” panes to float out of place. There needs to be a min width enforced for the parent panel such that tasks and announcements do not float out of place when the users reduce the browser window.

**Comment by natmote** [comment]
Even after #99, this still happens for me, even when it seems like there is enough room to lay stuff out.

Because this isn't a huge problem, though, I'm punting it to the second release.

**Comment by snuriel92** [comment]
So still fixed... just not pushed yet
