### ISSUE TITLE
Dashboard page should display the current house name rather than generic “Full House”. 

### ISSUE THREAD

**Issue by cmoiceanu** [Full-House-UW/fullhouse#81]
Link to screenshot
http://dl.dropbox.com/u/88614194/FullHouse_UI_Dashboard_MissingMyHouseName_001.PNG

I think the dashboard page should display the current house name rather than generic “Full House”.

**Comment by natmote** [comment]
I wouldn't categorize this as a bug. I think you're right, but I changed the label to "enhancement"

**Comment by cmoiceanu** [comment]
That is fine, but it will become a bug the moment we allow more than one house because we will not know which house we are looking at.

**Comment by creisman** [comment]
Are we planning on allowing multiple houses?

**Comment by snuriel92** [comment]
I think that for this release, no.
