### ISSUE TITLE
Adding Announcement needs expiration date

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#83]

**Comment by natmote** [comment]
It seems to me like this could be for next release.

**Comment by snuriel92** [comment]
That's why I labeled it as an enhancement ;)

**Comment by creisman** [comment]
The model needs to be updated first. Can you assign it back to me once the model is updated?

**Comment by snuriel92** [comment]
Also, need to remove title field from the model

**Comment by natmote** [comment]
conor, the ball is in your court with #123

**Comment by creisman** [comment]
What do I have to do to my database to recognize the new field? I keep
getting no such column: dashboard_announcement.expiration even after
running syncdb.

**Comment by j3ffml** [comment]
I was just about to open a ticket for this. syncdb does not add fields to existing tables, so we need to use south or some such thing to update.

**Comment by creisman** [comment]
I did:
manage.py reset dashboard
rm database
manage.py syncdb

This of course, will delete all the data, but oh well, it worked for my
personal account. Obviously that's bad to do to live (at least, it will be
if we ever have users ;) ).

**Comment by creisman** [comment]
@jlowdermilk, we're also removing the title field. Is there any harm from just deleting it from the model?

**Comment by j3ffml** [comment]
There should be no harm in deleting the field if it is no longer used. However the change won't be reflected  in the db unless we do a migration.

**Comment by creisman** [comment]
#130

**Comment by natmote** [comment]
@creisman The problem you experienced has been fixed as of #131.

I commented on #130, explaining how to do a migration when you remove the title.

**Comment by creisman** [comment]
You said you would do the migration, can you confirm this before I close this issue?

**Comment by natmote** [comment]
#132
