### ISSUE TITLE
Browser window resize causes the welcome page main logo to float out of place.

### ISSUE THREAD

**Issue by cmoiceanu** [Full-House-UW/fullhouse#84]
Link to screenshot 
http://dl.dropbox.com/u/88614194/FullHouse_UI_Welcome_FormResize_001.PNG

Browser window resize causes the welcome page main logo to float out of place. There needs to be a min width enforced for the parent panel such that logo does not float out of place when the users reduce the browser window.

**Comment by natmote** [comment]
I'm not sure that there's really a whole lot to be done on this issue. The fact is, if you make your window small enough, some stuff won't fit. I'm moving it to the second release, and we can evaluate it then.

**Comment by snuriel92** [comment]
fixed!
