### ISSUE TITLE
Dashboard Layout Bug

### ISSUE THREAD

**Issue by natmote** [Full-House-UW/fullhouse#87]
When I go to the dashboard in Chrome, the tasks pane is much lower than the announcements pane. If I go to a different page and then click back, it looks like it's supposed to, which is pretty weird.

http://i.imgur.com/96fH4.png

**Comment by natmote** [comment]
My resolution is 1600 by 1200, and I'm running Ubuntu 12.04

**Comment by cmoiceanu** [comment]
Is this the same issues as #80?

**Comment by natmote** [comment]
Oh, I didn't see yours before opening this. This occurs without resizing, though. They are likely manifestations of the same defect, so I'm not sure whether we should mark mine as a duplicate.

**Comment by snuriel92** [comment]
Ya, I think what we have is too size-specific... I'll look into it tonight and hopefully Janette will, too (I assigned one of us to each so we both look at it)

**Comment by natmote** [comment]
#99 fixes this issue for me
