### ISSUE TITLE
“Invalid invitation link” - should we make this friendlier?

### ISSUE THREAD

**Issue by cmoiceanu** [Full-House-UW/fullhouse#90]
If we sent a house invitation link to a user that is not a Full House registered user, when they try to validate and fail, should we redirect the new user to the registration page rather than just tell them the link is invalid?
At the minimum we should tell the user to register with Full House using the email address the invitation was sent to. 
It is not high priority for this milestone but I am adding this issue so we do not forget about it.

**Comment by j3ffml** [comment]
You actually only get that message if u are logged in and the invitation key doesn't exist, or the invitation was sent to a different email than the current user's email. I do agree that the process needs more streamlining and clarity

**Comment by j3ffml** [comment]
Closing this issue as the invalid link is only displayed if the user has an invalid key or is attempting to join a house they were not invited to.
