### ISSUE TITLE
Able to add blank announcement

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#97]
When I tried to create a blank announcement (blank in both fields), I got the correct "error"-thing where it tells me to enter in the two required fields. Then, when I went back to the Dashboard, the announcement is there, though blank.

http://oi45.tinypic.com/34e3gx2.jpg

(on the bright side, it makes the announcements and tasks line up well....)

**Comment by creisman** [comment]
This was a result of incorrectly using Announcement.objects.create instead of just making an Announcement object.

**Comment by creisman** [comment]
See #117
